### ISSUE TITLE
Be aware, it is detected a lot

### ISSUE THREAD

**Issue by TheCuteOwl** [TurtlesXD/Byte-Stealer#1]
try to fix that, i'm here to help :3

**Comment by TurtlesXD** [comment]
> try to fix that, i'm here to help :3

Thanks for the info, definately something I'm going to work first.

**Comment by 1yuub** [comment]
Hey TurtlesXD, I could use some assistance. Can you please let me know how I can get in touch with you? Thanks!

**Comment by TurtlesXD** [comment]
> Hey TurtlesXD, I could use some assistance. Can you please let me know how I can get in touch with you? Thanks!

I have discord, it's chickenpie8636

**Comment by TheCuteOwl** [comment]
the best username ever seen (no joke)
