### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MidnightApora** [TurtlesXD/Byte-Stealer#4]
where am i supposed to put the webhook in the logger.py and you tell me exactly where to put it

**Comment by TurtlesXD** [comment]
Sorry for being late, In the new script i have made, edit line 34 : `webhookurl='YourWebhookUrlHere'` Replace `'YourWebhookUrlHere'` to the actual url like so: `'https://discord.com/api/webhooks/83y2809y89dsf8y9'` and save.
