### ISSUE TITLE
Detected by avast

### ISSUE THREAD

**Issue by TheCuteOwl** [TurtlesXD/Byte-Stealer#5]
Well, if avast detect it try to make it a lil bit less detectable

**Comment by TurtlesXD** [comment]
i am currently tryna use pyarmor for obfuscation btw, and virsu total to check

**Comment by TheCuteOwl** [comment]
don't use this obfuscation it is pretty bad btw, and easily detectable

**Comment by TurtlesXD** [comment]
then what should i use?

**Comment by TurtlesXD** [comment]
btw windows defender doesnt detect it, neither does chrome or any browser, and thats my goal for it at the moment

**Comment by TheCuteOwl** [comment]
> then what should i use? Bc i dont wanna use any other script or 3rd party software

You could make ur own

**Comment by TheCuteOwl** [comment]
like just doing stuff with zlib and aes work xDD

**Comment by TheCuteOwl** [comment]
> 

do you have any virustotal url to check

**Comment by TheCuteOwl** [comment]
btw you should try to use less not built-in python module ^^

**Comment by TurtlesXD** [comment]
> btw you should try to use less not built-in python module ^^

Alr will do

**Comment by TurtlesXD** [comment]
> > 
> 
> do you have any virustotal url to check

https://www.virustotal.com/gui/file/2f42f133b3bef6977e06035955a1bc02416006126dc711b7bbc742588dfeee16

**Comment by TheCuteOwl** [comment]
BehavesLike.Win64.Dropper.vc
is, i guess the injector, try to make the url  a lil bit more hidden for an antivirus

**Comment by TheCuteOwl** [comment]
like

put the url reversed like

url = /wen/xoferif/SU-ne/gro.allizom.www//:sptth

and then if you want to call the url just do url[::-1]

**Comment by TurtlesXD** [comment]
> 

thanks for that

**Comment by TheCuteOwl** [comment]
no problem if i can help other, i've stopped working on mine so i help other xD

**Comment by TheCuteOwl** [comment]
bttw i have 2 other suggestion

**Comment by TheCuteOwl** [comment]
First, you should tell that's your Stealer is based of

Exodus and wasp so nobody will say "You skidded" and then a lil thing harder, is making the thread better, because the program could close before the thread are finished

**Comment by TurtlesXD** [comment]
> First, you should tell that's your Stealer is based of
> 
> Exodus and wasp so nobody will say "You skidded" and then a lil thing harder, is making the thread better, because the program could close before the thread are finished

btw whats exodus and wasp

**Comment by TheCuteOwl** [comment]
come discord i'm felix lol it would be easier :3
